### ISSUE TITLE
Problem with Example.m

### ISSUE THREAD

**Issue by maparedes** [esdalmaijer/EyeTribe-Toolbox-for-Matlab#1]
Hi everyone!

I have a problem with the toolbox for matlab.

when I execute the code in matlab using the examples that are includes in the  toolbox's folder, 

I have an error

> > EXAMPLE_PTB

Error uisng AsserMex (line 187)
Error in Screen (line 162)
Error in EXAMPLE_PTB (line 9)

or if I use:

> > EXAMPLE

Error using fwrite
Error in eyetribe_send_command (line 17)
Error in EXAMPLE (line 12)

....

I  installed the Pyschtoolbox, but I don't understand why not compile the examples.

thank for your help !

PS: sorry, I don't have a good english, I hope that you can understand me.

**Comment by esdalmaijer** [comment]
Thanks for the feedback!

From the first error, it seems like there might be something off with your installation of Matlab or Psychtoolbox. What happens if you type the following into your Command Window?

```
help Screen
```

Also, have you tried running a few of the PTB demos? These are included in the Psychtoolbox' directory (see here for more info: http://docs.psychtoolbox.org/PsychDemos).

Regarding the second error: Again, something quite unusual with a proper Matlab installation. Are you running the EyeTribe Server as well as the second server that is included in the EyeTribe Toolbox for Matlab?

Good luck!

**Comment by knaeckebrot0815** [comment]
You could try line 15, setting the screen to be used from 2 to 0: 
window = Screen('OpenWindow', 2) --> window = Screen('OpenWindow', 0)  % 0 = use primary monitor

Also make sure you have the Matlab "Instrument Control Toolbox" installed. Ewald, maybe you could add a comment to the description (and the paper) that this one is needed to control the eyetribe?

**Comment by esdalmaijer** [comment]
@knaeckebrot0815: Good point, that might be the issue on a setup with a single monitor. Thanks for pointing that out.

Name's Edwin, by the way, not Ewald ;)

**Comment by saltthehash** [comment]
Changing the 2 to a 0 willl probably fix it. However, to be certain, you can run the PTB command in matlab that shows the numbers of the screens:

```
>> Screen('Screens')
```

This will produce a list of the screen numbers for all displays connected. That way you can be certain of what PTB is detecting and numbering the displays as, though the default should be 0.

**Comment by knaeckebrot0815** [comment]
> > Name's Edwin, by the way, not Ewald ;)

--> My apologies!!

**Comment by esdalmaijer** [comment]
Closing the issue, as it should be solved by the suggestions above. Was waiting for confirmation from OP, but I guess they worked it out themselves :)
