### ISSUE TITLE
Calibration profile no longer works with EyeTribe 09.77.0

### ISSUE THREAD

**Issue by Beuks** [esdalmaijer/EyeTribe-Toolbox-for-Matlab#11]
I was forced to update EyeTribe because my the UI kept saying "device not connected" After I updated EyeTribe the detection of the EyeTribe was fine, but your calibration can no longer function to completion even for your example script

For some reason, at the third or fourth fixation point in the calibration process, it gets stuck, and starts spitting out the "Failed to start new point" / "Failed to end point" messages.

I've found your server extremely useful, any help would be greatly appreciated so I can complete the experiment I was working on.

Edit: The EyeTribe_Matlab_server says: ERROR in Calibration pointstart: could not parse message 'calibration pointstart;x=1728,y=108'

Edit: Was able to downgrade EyeTribe to 0.9.56 and there are no more issues at present

Cheers!
Steve

**Comment by esdalmaijer** [comment]
Thanks for the report!

This issue is either solved with today's commit, or it originates from the same problem as reported in issue #8 (which I will look into shortly). I'm closing this for now; but pay attention to issue #8 is you still experience any problems after downloading the current code and executables.

Cheers,
Edwin
